name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main
        with:
          persist-credentials: true

      - name: Refresh
        run: pnpm run refresh

      - name: Commit
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update data [ci skip]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
